title: Indrajeet Jadhav
logo: /assets/img/2521 - Copy.jpg
description: I am a Data scientist with 3.5+ working on ML, NLP and time series related problems.
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
