title: <p align="center"> Indrajeet Jadhav </p>
logo: /assets/img/2521 - Copy.jpg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/indrajeet-jadhav-43124378/">LinkedIn</a> |
  <a href="https://github.com/jadhavib1908">GitHub</a>
  
  <br>
  I am a Data scientist with 3.5+ working on ML, NLP and time series related problems.
  </br>
  </p>

theme: jekyll-theme-minimal
