title: <p align="center"> Indrajeet Jadhav </p>
logo: /assets/img/2521 - Copy.jpg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/indrajeet-jadhav-43124378/">LinkedIn</a> |
  <a href="https://github.com/jadhavib1908">GitHub</a>
  
  <br>
  I am data scientist with expertise in NLP, Machine Learning and Time Series Analysis.
  </br>
  <br>
  Experienced in developing and implementing data-driven solutions to real-world problems
  </br>
  </p>

theme: jekyll-theme-minimal
